
***  Constant sample
mdesc ln_harvest_value_cp year ln_plot_area ln_labor_days_nonhired ln_labor_days_nonhired ln_seed_value_cp ln_hired_labor_value_constant ln_inorganic_fert_value_con  ag_asset_index used_pesticides organic_fertilizer irrigated intercropped crop_shock hh_shock livestock hh_size formal_education_manager female_manager age_manager hh_electricity_access  urban plot_owned miss_harvest_value_cp ln_dist_road ln_dist_popcenter soil_fertility_index ln_elevation tot_precip_sd_season cluster_id  Country Main_crop agro_ecological_zone temperature_sd_season temperature_min_season temperature_max_season temperature_mean_season temperature_above25C_season temperature_above30C_season

replace crop_shock = . if crop_shock==.a
drop if inlist(., ln_harvest_value_cp, year, ln_plot_area,ln_labor_days_nonhired, ln_seed_value_cp, ln_hired_labor_value_constant, ln_inorganic_fert_value_con, ag_asset_index, used_pesticides,organic_fertilizer,irrigated,intercropped,crop_shock,hh_shock,livestock,hh_size,formal_education_manager,female_manager,age_manager,hh_electricity_access,urban,plot_owned,miss_harvest_value_cp, ln_dist_road, ln_dist_popcenter, soil_fertility_index, ln_elevation, tot_precip_sd_season, cluster_id, Country, Main_crop, agro_ecological_zone, temperature_sd_season, temperature_min_season, temperature_max_season, temperature_mean_season, temperature_above25C_season, temperature_above30C_season, pw, strataid)



*** squared weather vars
foreach var of varlist temperature_sd_season temperature_min_season temperature_max_season temperature_mean_season temperature_above25C_season temperature_above30C_season temperature_above35C_season temperature_below15C_season temperature_LRmean_season temperature_lagP_av3months temperature_lagP_av6months temperature_meanmonth_lag1P temperature_meanmonth_lag2P temperature_meanmonth_lag3P temperature_meanmonth_lead1P temperature_meanmonth_lead2P temperature_meanmonth_lead3P temp_meanmonthH temperature_meanmonthP tot_precip_sd_season tot_precip_cumul_season tot_precip_below5p_season  tot_precip_below1p_season tot_precip_0precip_season tot_precip_above95p_season tot_precip_above99p_season tot_precip_LRmean_season tot_precip_lagP_cumul3months tot_precip_lagP_cumul6months tot_precip_cumulmonth_lag1P tot_precip_cumulmonth_lag2P tot_precip_cumulmonth_lag3P tot_precip_cumulmonth_lead1P tot_precip_cumulmonth_lead2P tot_precip_cumulmonth_lead3P tot_precip_cumulmonthH tot_precip_cumulmonthP temperature_meanmonth_lag1H temperature_meanmonth_lag2H temperature_meanmonth_lag3H temperature_meanmonth_lag4H temperature_meanmonth_lag5H temperature_meanmonth_lag6H tot_precip_cumulmonth_lag1H tot_precip_cumulmonth_lag2H tot_precip_cumulmonth_lag3H tot_precip_cumulmonth_lag4H tot_precip_cumulmonth_lag5H tot_precip_cumulmonth_lag6H {	
	gen `var'2 = c.`var'#c.`var'
}

	
*** Creating globals
global inputs ln_plot_area ln_labor_days_nonhired ln_hired_labor_value ln_seed_value ln_inorganic_fertilizer_value  ag_asset_index

global inputs_cp ln_plot_area ln_labor_days_nonhired ln_seed_value_cp ln_hired_labor_value_constant ln_inorganic_fert_value_con  ag_asset_index

global inputs_perld_cp ln_plot_area ln_total_labor_days_tot ln_seed_value_perld_cp ln_hired_labor_value_perld_cp ln_inorg_fert_value_perld_cp   ag_asset_index

global inputs_perseed_cp ln_plot_area ln_labor_days_nonhired_perseed ln_seed_value_cp_tot ln_hired_labor_value_perseed_cp  ln_inorg_fert_value_perseed_cp   ag_asset_index

global Dinputs_cp Dln_plot_area Dln_labor_days_nonhired Dln_seed_value_cp Dln_hired_labor_value_constant Dln_inorganic_fert_value_con  Dag_asset_index 

global Dinputs_perld Dln_plot_area Dln_labor_days_nonhired_perld Dln_hired_labor_value_perld  Dln_seed_value_perld   Dln_inorg_fert_value_perld      Dag_asset_index  

global FE c.year i.Country i.Main_crop 
global FE_withincountry c.year i.Main_crop 
global FE_plotcrop c.year i.Country i.crop_code
global FE_withincountry_plotcrop c.year i.crop_code 

global controls used_pesticides organic_fertilizer irrigated intercropped crop_shock hh_shock livestock hh_size formal_education_manager female_manager age_manager hh_electricity_access  urban plot_owned miss_harvest_value

global controls_cp used_pesticides organic_fertilizer irrigated intercropped crop_shock hh_shock livestock hh_size formal_education_manager female_manager age_manager hh_electricity_access urban plot_owned miss_harvest_value_cp

global Dcontrols_cp Dused_pesticides Dorganic_fertilizer Dirrigated Dintercropped  Dhh_shock Dlivestock Dhh_size Dformal_education_manager Dfemale_manager Dage_manager Dhh_electricity_access  Durban Dplot_owned Dmiss_harvest_value_cp 

global Dgeo Dln_dist_road Dln_dist_popcenter Dsoil_fertility_index Dln_elevation 

global geo_test 311.agro_ecological_zone 312.agro_ecological_zone 313.agro_ecological_zone 321.agro_ecological_zone 322.agro_ecological_zone 323.agro_ecological_zone 324.agro_ecological_zone ln_dist_road ln_dist_popcenter soil_fertility_index ln_elevation  

global geo i.agro_ecological_zone ln_dist_road ln_dist_popcenter soil_fertility_index ln_elevation  

global weather tot_precip_sd_season  tot_precip_cumul_season tot_precip_below1p_season tot_precip_above99p_season temperature_sd_season  temperature_above30C_season  temperature_below15C_season tot_precip_cumulmonthP tot_precip_cumulmonth_lag1P tot_precip_cumulmonth_lag2P tot_precip_cumulmonthH tot_precip_cumulmonth_lag1H tot_precip_cumulmonth_lag2H  

global weather2 
foreach var in  $weather {
	global weather2 $weather2 `var'2
}

global weather tot_precip_sd_season tot_precip_cumul_season tot_precip_below1p_season tot_precip_above99p_season temperature_sd_season  temperature_above30C_season  temperature_below15C_season tot_precip_cumulmonthP tot_precip_cumulmonth_lag1P tot_precip_cumulmonth_lag2P tot_precip_cumulmonthH tot_precip_cumulmonth_lag1H tot_precip_cumulmonth_lag2H temperature_meanmonthP  temp_meanmonthH 


* define set of variables to be selected 
global controls_all used_pesticides organic_fertilizer irrigated intercropped hh_shock livestock hh_size formal_education_manager female_manager age_manager hh_electricity_access urban plot_owned miss_harvest_value sorghum_plot wheat_plot maize_plot hh_primary_education hh_formal_education hh_asset_index twi season_length hh_dependency_ratio tractor


global weather_all_nodummies temperature_sd_season temperature_min_season temperature_max_season temperature_mean_season temperature_above25C_season temperature_above30C_season temperature_above35C_season temperature_below15C_season temperature_LRmean_season temperature_lagP_av3months temperature_lagP_av6months temperature_meanmonth_lag1P temperature_meanmonth_lag2P temperature_meanmonth_lag3P temperature_meanmonth_lead1P temperature_meanmonth_lead2P temperature_meanmonth_lead3P temp_meanmonthH temperature_meanmonthP tot_precip_cumul_season tot_precip_below5p_season  tot_precip_below1p_season tot_precip_0precip_season tot_precip_above95p_season tot_precip_above99p_season tot_precip_LRmean_season tot_precip_lagP_cumul3months tot_precip_lagP_cumul6months tot_precip_cumulmonth_lag1P tot_precip_cumulmonth_lag2P tot_precip_cumulmonth_lag3P tot_precip_cumulmonth_lead1P tot_precip_cumulmonth_lead2P tot_precip_cumulmonth_lead3P tot_precip_cumulmonthH tot_precip_cumulmonthP temperature_meanmonth_lag1H temperature_meanmonth_lag2H temperature_meanmonth_lag3H temperature_meanmonth_lag4H temperature_meanmonth_lag5H temperature_meanmonth_lag6H tot_precip_cumulmonth_lag1H tot_precip_cumulmonth_lag2H tot_precip_cumulmonth_lag3H tot_precip_cumulmonth_lag4H tot_precip_cumulmonth_lag5H tot_precip_cumulmonth_lag6H temperature_sd_season2 temperature_min_season2 temperature_max_season2 temperature_mean_season2 temperature_above25C_season2 temperature_above30C_season2 temperature_above35C_season2 temperature_below15C_season2 temperature_LRmean_season2 temperature_lagP_av3months2 temperature_lagP_av6months2 temperature_meanmonth_lag1P2 temperature_meanmonth_lag2P2 temperature_meanmonth_lag3P2 temperature_meanmonth_lead1P2 temperature_meanmonth_lead2P2 temperature_meanmonth_lead3P2 temp_meanmonthH2 temperature_meanmonthP2 tot_precip_cumul_season2 tot_precip_below5p_season2 tot_precip_below1p_season2 tot_precip_0precip_season2 tot_precip_above95p_season2 tot_precip_above99p_season2 tot_precip_LRmean_season2 tot_precip_lagP_cumul3months2 tot_precip_lagP_cumul6months2 tot_precip_cumulmonth_lag1P2 tot_precip_cumulmonth_lag2P2 tot_precip_cumulmonth_lag3P2 tot_precip_cumulmonth_lead1P2 tot_precip_cumulmonth_lead2P2 tot_precip_cumulmonth_lead3P2 tot_precip_cumulmonthH2 tot_precip_cumulmonthP2 temperature_meanmonth_lag1H2 temperature_meanmonth_lag2H2 temperature_meanmonth_lag3H2 temperature_meanmonth_lag4H2 temperature_meanmonth_lag5H2 temperature_meanmonth_lag6H2 tot_precip_cumulmonth_lag1H2 tot_precip_cumulmonth_lag2H2 tot_precip_cumulmonth_lag3H2 tot_precip_cumulmonth_lag4H2 tot_precip_cumulmonth_lag5H2 tot_precip_cumulmonth_lag6H2 


global Dweather_all 
foreach var in $weather_all {
	global Dweather_all  D`var' 
}
global weather_all $weather_all_nodummies
foreach var in $weather_all_nodummies {
 global weather_all $weather_all i.country_dummy1#c.`var' i.country_dummy2#c.`var' i.country_dummy3#c.`var' i.country_dummy4#c.`var' i.country_dummy5#c.`var' i.country_dummy6#c.`var'
 }


global geo_testMWI  ln_dist_road ln_dist_popcenter soil_fertility_index ln_elevation  312.agro_ecological_zone 313.agro_ecological_zone 322.agro_ecological_zone 323.agro_ecological_zone
global geo_testMLI  ln_dist_road ln_dist_popcenter soil_fertility_index ln_elevation 311.agro_ecological_zone  312.agro_ecological_zone 313.agro_ecological_zone 
global geo_testNGR ln_dist_road ln_dist_popcenter soil_fertility_index ln_elevation 311.agro_ecological_zone  312.agro_ecological_zone 321.agro_ecological_zone 
global geo_testNGA ln_dist_road ln_dist_popcenter soil_fertility_index ln_elevation   312.agro_ecological_zone 313.agro_ecological_zone 314.agro_ecological_zone 323.agro_ecological_zone 
global geo_testTZA ln_dist_road ln_dist_popcenter soil_fertility_index ln_elevation   312.agro_ecological_zone 313.agro_ecological_zone 314.agro_ecological_zone 322.agro_ecological_zone 323.agro_ecological_zone 324.agro_ecological_zone 
global geo_testUGA ln_dist_road ln_dist_popcenter soil_fertility_index ln_elevation    313.agro_ecological_zone 314.agro_ecological_zone 323.agro_ecological_zone 324.agro_ecological_zone 

global controls_continuous temperature_sd_season temperature_min_season temperature_max_season temperature_mean_season temperature_above25C_season temperature_above30C_season temperature_above35C_season temperature_below15C_season temperature_LRmean_season temperature_lagP_av3months temperature_lagP_av6months temperature_meanmonth_lag1P temperature_meanmonth_lag2P temperature_meanmonth_lag3P temperature_meanmonth_lead1P temperature_meanmonth_lead2P temperature_meanmonth_lead3P temp_meanmonthH temperature_meanmonthP tot_precip_cumul_season tot_precip_below5p_season  tot_precip_below1p_season tot_precip_0precip_season tot_precip_above95p_season tot_precip_above99p_season tot_precip_LRmean_season tot_precip_lagP_cumul3months tot_precip_lagP_cumul6months tot_precip_cumulmonth_lag1P tot_precip_cumulmonth_lag2P tot_precip_cumulmonth_lag3P tot_precip_cumulmonth_lead1P tot_precip_cumulmonth_lead2P tot_precip_cumulmonth_lead3P tot_precip_cumulmonthH tot_precip_cumulmonthP temperature_meanmonth_lag1H temperature_meanmonth_lag2H temperature_meanmonth_lag3H temperature_meanmonth_lag4H temperature_meanmonth_lag5H temperature_meanmonth_lag6H tot_precip_cumulmonth_lag1H tot_precip_cumulmonth_lag2H tot_precip_cumulmonth_lag3H tot_precip_cumulmonth_lag4H tot_precip_cumulmonth_lag5H tot_precip_cumulmonth_lag6H temperature_sd_season2 temperature_min_season2 temperature_max_season2 temperature_mean_season2 temperature_above25C_season2 temperature_above30C_season2 temperature_above35C_season2 temperature_below15C_season2 temperature_LRmean_season2 temperature_lagP_av3months2 temperature_lagP_av6months2 temperature_meanmonth_lag1P2 temperature_meanmonth_lag2P2 temperature_meanmonth_lag3P2 temperature_meanmonth_lead1P2 temperature_meanmonth_lead2P2 temperature_meanmonth_lead3P2 temp_meanmonthH2 temperature_meanmonthP2 tot_precip_cumul_season2 tot_precip_below5p_season2 tot_precip_below1p_season2 tot_precip_0precip_season2 tot_precip_above95p_season2 tot_precip_above99p_season2 tot_precip_LRmean_season2 tot_precip_lagP_cumul3months2 tot_precip_lagP_cumul6months2 tot_precip_cumulmonth_lag1P2 tot_precip_cumulmonth_lag2P2 tot_precip_cumulmonth_lag3P2 tot_precip_cumulmonth_lead1P2 tot_precip_cumulmonth_lead2P2 tot_precip_cumulmonth_lead3P2 tot_precip_cumulmonthH2 tot_precip_cumulmonthP2 temperature_meanmonth_lag1H2 temperature_meanmonth_lag2H2 temperature_meanmonth_lag3H2 temperature_meanmonth_lag4H2 temperature_meanmonth_lag5H2 temperature_meanmonth_lag6H2 tot_precip_cumulmonth_lag1H2 tot_precip_cumulmonth_lag2H2 tot_precip_cumulmonth_lag3H2 tot_precip_cumulmonth_lag4H2 tot_precip_cumulmonth_lag5H2 tot_precip_cumulmonth_lag6H2 temperature_maxmax_season temperature_maxmin_season temperature_minmax_season temperature_minmin_season temperature_maxrange_season precipitation_maxmax_season max_5day_precip_season pii_season days_above_10mm_season days_above_20mm_season dry_spell_season wet_spell_season ln_dist_road ln_dist_popcenter soil_fertility_index ln_elevation 
